### PR TITLE
Include sub modules

### PR DESCRIPTION
**Pull request by blackbaud-conorwright**
Resolves: #6 
Docs: N/A

### CODE REVIEW

**Review by Blackbaud-AlexKingman — DISMISSED** [review]
LGTM

**Review by Blackbaud-SteveBrush — CHANGES_REQUESTED** [review]
It seems that I should be able to write my **app-extras.module.ts** file like this, and it would work:

```
import {
  NgModule
} from '@angular/core';

import {
  SkyListModule,
  SkyListToolbarModule
} from '@skyux/list-builder';

import {
  SkyListViewGridModule
} from './public';

@NgModule({
  exports: [
    SkyListModule,
    SkyListToolbarModule,
    SkyListViewGridModule
  ]
})
export class AppExtrasModule { }
```

Is that correct?

**Comment by blackbaud-conorwright** [comment]
@Blackbaud-SteveBrush Yes, that should work as long as you only use what they provide. However I don't think you can realistically use the SkyListViewGridModule without using SkyGridModule

Here is the one I used for testing:
```

@NgModule({
  exports: [
    SkyAlertModule,
    SkyAvatarModule,
    SkyErrorModule,
    SkyKeyInfoModule,
    SkyModalModule,
    SkyListModule,
    SkyListViewGridModule,
    SkyWaitModule,
    SkyListSecondaryActionsModule,
    SkyListToolbarModule,
    SkyGridModule,
    SkyListPagingModule
  ]
})
export class AppExtrasModule { }
```

Is yours not working? I'll try to reduce mine down and see

**Comment by blackbaud-conorwright** [comment]
@Blackbaud-SteveBrush I have mine working with just:
```

@NgModule({
  exports: [
    SkyListModule,
    SkyListViewGridModule,
    SkyListToolbarModule,
    SkyGridModule
  ]
})
export class AppExtrasModule { }
```

You can see it here: https://github.com/blackbaud-conorwright/skyux-spa-my-test

I presume your issue is not having SkyGridModule, but I can see a good case for including that in the exports of SkyListViewGridModule. Though it's weird since it isn't in that lib ;p Do you think we should include that in the exports of SkyListViewGridModule?

**Comment by blackbaud-conorwright** [comment]
@Blackbaud-SteveBrush I have mine working with just:
```

@NgModule({
  exports: [
    SkyAlertModule,
    SkyAvatarModule,
    SkyErrorModule,
    SkyKeyInfoModule,
    SkyModalModule,
    SkyListModule,
    SkyListViewGridModule,
    SkyWaitModule,
    SkyListSecondaryActionsModule,
    SkyListToolbarModule,
    SkyGridModule,
    SkyListPagingModule
  ]
})
export class AppExtrasModule { }
```

You can see it here: https://github.com/blackbaud-conorwright/skyux-spa-my-test

I presume your issue is not having SkyGridModule, but I can see a good case for including that in the exports of SkyListViewGridModule. Though it's weird since it isn't in that lib ;p Do you think we should include that in the exports of SkyListViewGridModule?

**Comment by Blackbaud-SteveBrush** [comment]
The following **app-extras.module.ts** file will fail to serve (notice the barrel import for `SkyListViewGridModule`):

```
import {
  NgModule
} from '@angular/core';

import {
  SkyGridModule
} from '@skyux/grids';

import {
  SkyListModule,
  SkyListToolbarModule
} from '@skyux/list-builder';

import {
  SkyListViewGridModule
} from './public';

@NgModule({
  exports: [
    SkyGridModule,
    SkyListModule,
    SkyListToolbarModule,
    SkyListViewGridModule
  ]
})
export class AppExtrasModule { }
```

**Comment by Blackbaud-SteveBrush** [comment]
@blackbaud-conorwright Looks like we have a few linting errors during the build.

**Comment by blackbaud-conorwright** [comment]
@Blackbaud-SteveBrush Ah yeah, I meant to move those up, but never pasted them ;p
back in now

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Pull request merged**
